id: bd3bf28f8953476a83a9a13066939c62
initial_creation_type: ocr
source_metadata:
  volumes:
    580f1cb64bc94cf5941e3ea3daccf1da:
      base_file: v064.txt
      image_group_id: I1PD95910
      title: ''
      total_pages: 1498
      volume_number: 65
